service: hyperspace-api

plugins:
  - serverless-python-requirements
  - serverless-apigw-binary
provider:
  name: aws
  stage: prod
  runtime: python3.10
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:ListTables
          Resource: '*'
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: 'arn:aws:dynamodb:*:*:table/musbb_murd_*'
        - Effect: Allow
          Action:
            - s3:*
          Resource: 'arn:aws:s3:::${env:MakurspaceStaticAssets}/*'
        - Effect: Allow
          Action:
            - s3:*
          Resource: 'arn:aws:s3:::${env:MakurspaceEnv}/*'
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: '*'
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: 'arn:aws:lambda:*:*:function:stl_to_image'

package:
  individually: true
  patterns:
    - '!./**'

functions:
  hyperspace_cronitor:
    name: hyperspace_cronitor
    handler: hyperspace.cronitor.lambda_handler
    memorySize: 128
    timeout: 120
    package:
      patterns:
        - 'hyperspace/**'
    environment:
      MakurspaceStaticAssets: ${env:MakurspaceStaticAssets} 
    events:
      - schedule: rate(1 day)

  hyperspace_api:
    name: hyperspace_api
    handler: hyperspace.api.lambda_handler
    memorySize: 128
    timeout: 30
    package:
      patterns:
        - 'hyperspace/**'
    environment:
      MakurspaceStaticAssets: ${env:MakurspaceStaticAssets} 
    events:
      - http:
          path: /rest/bountyboard
          method: get
      - http:
          path: /rest/bountyboard/{bounty_id}
          method: get
      - http:
          path: /rest/bounties_in_progress
          method: get
      - http:
          path: /rest/bounty_portfolio
          method: get
      - http:
          path: /rest/upload_reference_material.js
          method: get
      - http:
          path: /rest/reference_material/{bounty_id}/{refmat_filename}
          method: get
      - http:
          path: /rest/maker_registration
          method: post
      - http:
          path: /rest/maker_registration/{maker_id}
          method: get
      - http:
          path: /rest/bounty_form/{bounty_id}/{refmat_filename}
          method: get
      - http:
          path: /rest/bounty_form
          method: post
      - http:
          path: /rest/bounty_confirmation/{bounty_confirmation_id}
          method: get
      - http:
          path: /rest/completed_bounty_form
          method: post
      - http:
          path: /rest/completed_bounty_confirmation/{bounty_confirmation_id}
          method: get
      - http:
          path: /rest/ask_recipient/{bounty_id}
          method: get
      - http:
          path: /rest/ask_recipient/{bounty_id}
          method: post
      - http:
          path: /rest/question/{question_id}
          method: get
      - http:
          path: /rest/question/{question_id}
          method: post
      - http:
          path: /rest/edit_bounty/{bounty_id}
          method: get
      - http:
          path: /rest/edit_bounty/{bounty_id}
          method: post
      - http:
          path: /rest/submit_bounty_edits/{bounty_edit_id}
          method: get
      - http:
          path: /rest/confirm_bounty_edits/{bounty_edit_confirmation_id}
          method: get
      - http:
          path: /rest/call_bounty/{bounty_id}
          method: get
      - http:
          path: /rest/call_bounty/{bounty_id}
          method: post
      - http:
          path: /rest/call_bounty_confirm/{call_confirmation_id}
          method: get
      - http:
          path: /rest/relinquish_bounty/{bounty_id}
          method: get
      - http:
          path: /rest/bounty_up/{bounty_id}
          method: get
      - http:
          path: /rest/bounty_up
          method: post
      - http:
          path: /rest/claim_bounty/{bounty_id}
          method: get
      - http:
          path: /rest/claim_bounty
          method: post
      - http:
          path: /rest/claim_bounty_confirm/{claim_confirmation_id}
          method: get
      - http:
          path: /rest/rendered_bountyboard
          method: get
      - http:
          path: /rest/rendered_bounties_in_progress
          method: get
      - http:
          path: /rest/rendered_bounty_portfolio
          method: get
      - http:
          path: /rest/rendered_bounty/{bounty_id}
          method: get
      - http:
          path: /rest/rendered_bounty_refmat/{bounty_id}
          method: get


custom:
  pythonRequirements:
    dockerizePip: non-linux
    useDownloadCache: false
    noDeploy: []
  apigwBinary:
    types:
      - 'multipart/form-data'
