service: hyperspace-api

plugins:
  - serverless-python-requirements
  - serverless-apigw-binary
  - serverless-s3-sync
provider:
  name: aws
  stage: prod
  runtime: python3.8
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:ListTables
      Resource: '*'
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: 'arn:aws:dynamodb:*:*:table/musbb_murd_*'
    - Effect: Allow
      Action:
        - s3:*
      Resource: 'arn:aws:s3:::${env:MakurspaceStaticAssets}/*'
    - Effect: Allow
      Action:
        - s3:*
      Resource: 'arn:aws:s3:::${env:MakurspaceEnv}/*'
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: '*'

resources:
  Resources:
    MakUrSpaceStaticAssets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:MakurspaceStaticAssets}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

package:
  individually: true
  exclude:
    - ./**

functions:
  hyperspace_api:
    name: hyperspace_api
    handler: hyperspace.api.lambda_handler
    memorySize: 128
    timeout: 30
    package:
      include:
        - hyperspace/**
    events:
      - http:
          path: /rest/bountyboard
          method: get
      - http:
          path: /rest/bountyboard/{bounty_id}
          method: get
      - http:
          path: /rest/bounties_in_progress
          method: get
      - http:
          path: /rest/bounty_portfolio
          method: get
      - http:
          path: /rest/upload_reference_material.js
          method: get
      - http:
          path: /rest/reference_material/{bounty_id}/{refmat_filename}
          method: get
      - http:
          path: /rest/maker_registration
          method: post
      - http:
          path: /rest/maker_registration/{maker_id}
          method: get
      - http:
          path: /rest/bounty_form/{bounty_id}/{refmat_filename}
          method: get
      - http:
          path: /rest/bounty_form
          method: post
      - http:
          path: /rest/bounty_confirmation/{bounty_confirmation_id}
          method: get
      - http:
          path: /rest/bounty_confirmation/{bounty_confirmation_id}
          method: post
      - http:
          path: /rest/edit_bounty/{bounty_id}
          method: get
      - http:
          path: /rest/edit_bounty/{bounty_id}
          method: post
      - http:
          path: /rest/call_bounty/{bounty_id}
          method: get
      - http:
          path: /rest/call_bounty/{bounty_id}
          method: post
      - http:
          path: /rest/call_bounty_confirm/{call_confirmation_id}
          method: get
      - http:
          path: /rest/relinquish_bounty/{bounty_id}
          method: get
      - http:
          path: /rest/bounty_wip/{bounty_id}
          method: get
      - http:
          path: /rest/bounty_wip
          method: post
      - http:
          path: /rest/claim_bounty/{bounty_id}
          method: get
      - http:
          path: /rest/claim_bounty
          method: post
      - http:
          path: /rest/rendered_bountyboard
          method: get
      - http:
          path: /rest/rendered_bounties_in_progress
          method: get
      - http:
          path: /rest/rendered_bounty_portfolio
          method: get
      - http:
          path: /rest/rendered_bounty/{bounty_id}
          method: get

custom:
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy: []
  apigwBinary:
    types:
      - 'multipart/form-data'
  s3Sync:
    - bucketName: ${env:MakurspaceStaticAssets}
      localDir: ./static
      deleteRemoved: false
      acl: public-read
