service: hyperspace-server

plugins:
  - serverless-python-requirements
provider:
  name: aws
  stage: prod
  runtime: python3.8
  region: us-east-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::makurspace/server/*"
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  hyperspace_server:
    name: hyperspace_server
    handler: hyperspace_server.lambda_handler
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: /
          method: get
      - http:
          path: /static/{path}
          method: get
      - http:
          path: /maker_module/{gpid}
          method: get



custom:
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy: []

