service: makurspace-static-server

plugins:
  - serverless-s3-sync
provider:
  name: aws
  stage: prod
  region: us-east-1



custom:
  s3Sync:
    - bucketName: ${env:MakurspaceStaticAssets}
      localDir: ./
      deleteRemoved: false
      acl: public-read


