service: hyperspace-api

plugins:
  - serverless-python-requirements
  - serverless-apigw-binary
provider:
  name: aws
  stage: prod
  runtime: python3.8
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:ListTables
      Resource: '*'
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: 'arn:aws:dynamodb:*:*:table/musbb_murd_*'
    - Effect: Allow
      Action:
        - s3:*
      Resource: 'arn:aws:s3:::makurspace-static-assets/*'
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: '*'



functions:
  hyperspace_api:
    name: hyperspace_api
    handler: hyperspace_api.lambda_handler
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: /rest/bounty_form
          method: post
      - http:
          path: /rest/bounty_form
          method: get
      - http:
          path: /rest/bountyboard
          method: post
      - http:
          path: /rest/bountyboard/{bounty_name}
          method: get
      - http:
          path: /rest/bountyboard
          method: get


custom:
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy: []
  apigwBinary:
    types:
      - 'multipart/form-data'

